### ISSUE TITLE
Fatal error : "assertion 'SECRET_IS_COLLECTION (collection)' failed"

### ISSUE THREAD

**Issue by danbaghilovici** [skarva/kipeltip#12]
After filling the form for a new login entry and submiting it, nothing happens and I get an empty list.
Running the app from the terminal shows me:
`
dntzbgh@X250:~$ com.github.skarva.lockbox 
[NOTIFY 17:27:40.606524] Changed clear clipboard setting
[NOTIFY 17:27:40.606750] Changed clear clipboard setting
[FATAL 17:28:06.519551] secret_item_create: assertion 'SECRET_IS_COLLECTION (collection)' failed

`

**Comment by zeebok** [comment]
Just to be sure I know how to start approaching this, are you running this on Elementary OS or a different distro?

**Comment by danbaghilovici** [comment]
Sorry for late response.
Yes , I'm running elementary OS 5.0 Juno (Linux 4.15.0-65-generic) (GTK 3.22.30)

**Comment by ryonakano** [comment]
I guess this is a duplicate of #11,

**Comment by zeebok** [comment]
I am thinking that too so I will close this one and do the rest of the work in #11
