### ISSUE TITLE
privacy

### ISSUE THREAD

**Issue by ashadnasim52** [skarva/kipeltip#13]
How can a user be sure that their credentials are not misused and leaked from your app.

If we cannot be sure of that all credentials are safe in your application, then what is the purpose of using it,

**Comment by zeebok** [comment]
Well the app itself can't do too much to ensure this. A welcome message that says "Just trust us!" I don't think would do the trick. But with the code open source, you can find that it simply uses the long running libsecret, or just Secret, which what the gnome keyring is based on, and what several other applications use for storing credentials.
